### ISSUE TITLE
when wallet is opened in browser remotely it requires access to location

### ISSUE THREAD

**Issue by tonowie** [bad-weather-corp/NEMWallet#21]
opening wallet for example from https://wallet.mynem.cz requests location info from user. we do not use that for anything so why ask for it?

**Comment by yaaccount** [comment]
Without digging deeper, it seems it is used to identify/use NISes geographically closest to the user.

**Comment by tonowie** [comment]
ok I was worried it was requested without real use. I can live with what is there :)
