### ISSUE TITLE
Cold wallet support for all functionality

### ISSUE THREAD

**Issue by tonowie** [bad-weather-corp/NEMWallet#9]
since transaction can be serialized we can export it as a QR, then import to cold wallet for signing and get back to be announced to the network

**Comment by tonowie** [comment]
I am closing this as we already have base functionality merged into the dev branch and there is project to track finalization of the feature

**Comment by yaaccount** [comment]
NemProject/NanoWallet#437

**Comment by yaaccount** [comment]
NemProject/NanoWallet#394
